name: Update AWS infrastructure template
description: AWS Infrastructure update template.
title: "Update X from `y` to `z`"
labels: ["update"]
body:
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Add some details about the update.
      placeholder: Tell us what you see!
      value: "A new version of X has been released."
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any notes go here.
      value: ""
  - type: textarea
    id: tasklist
    attributes:
      label: Task list
      description: "- [ ] Check the change log\n- [ ] Determine and report any breaking changes\n- [ ] Apply into `staging` and verify everything works\n- [ ] Apply into `production` and verify everything works"
  - type: textarea
    id: useful-resources
    attributes:
      label: Useful resources
      description: Place any useful links or resources here.
