name: Postgres

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:

      - name: Install Postgres 17
        run: |
          # Setup Postgresql Apt repo
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
          echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/apt.postgresql.org.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          # Install updated version of Postgresql
          sudo apt-get update
          sudo apt-get --yes install postgresql-client-17
          # Add PostgreSQL 17 binaries to PATH
          echo "export PATH=/usr/lib/postgresql/17/bin:\$PATH" >> "$GITHUB_ENV"


      - name: Check version
        run: |
          psql --version
          pg_dump --version
          pg_restore --version
