on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate_token.outputs.token }}
    steps:
      - id: generate_token
        run: |
          echo "::add-mask::my_test_token_123456"
          echo "token=my_test_token_123456" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Received masked token: ${{ needs.job1.outputs.token }}"
          if [[ "my_test_token_123456" == "${{ needs.job1.outputs.token }}" ]]; then
              echo "Received token was my_test_token_123456"
          else
              echo "Uhm.. What happened here?"
              exit 1
          fi
  
